#  spring.application.name=demo

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: "root"
#    password: "yeelam0208"
  # Use H2 in-memory database for testing
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

    spring:
     datasource:
      jpa:
       show-sql: true
       hibernate:
         ddl-auto: update
